### ISSUE TITLE
Move parse_top_level_import_name from Pyodide build

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide-lock#7]
When creating the `pyodide-lock.json` we would need to be able to identify import names for a given pure Python wheel. 
So it would be useful to move the [`parse_top_level_import_name`](https://github.com/pyodide/pyodide/blob/50b5e1ccb6863507c46f832adb743be0917b4dc1/pyodide-build/pyodide_build/common.py#L56C5-L56C32) function + the associated tests from Pyodide build here.

Then at a later stage use it in `pyodide-build` imported from this package.

**Comment by ryanking13** [comment]
Sounds good to me.

**Comment by rth** [comment]
@juntyr FYI a small good first issue.
